// electron/llm/training/intentDataset.ts
// Training dataset for SetFit intent classifier.
// 800+ real-world and synthetic examples specific to Natively's interview context.

import type { ConversationIntent } from '../IntentClassifier';

export interface TrainingExample {
  text: string;
  label: ConversationIntent;
  source: 'real' | 'synthetic' | 'augmented';
  metadata?: {
    originalText?: string;
    augmentationType?: string;
    difficulty?: 'easy' | 'medium' | 'hard';
    [key: string]: any;
  };
}

const EXAMPLES: TrainingExample[] = [
  // === BEHAVIORAL (100 examples) ===
  { text: "Tell me about a time you had to deal with a difficult stakeholder.", label: "behavioral", source: "real" },
  { text: "Describe a situation where you had to make a decision with incomplete information.", label: "behavioral", source: "real" },
  { text: "Give me an example of a project you led from start to finish.", label: "behavioral", source: "real" },
  { text: "Walk me through a time you failed and what you learned from it.", label: "behavioral", source: "real" },
  { text: "Tell me about a time you had to influence someone without authority.", label: "behavioral", source: "real" },
  { text: "Describe a conflict you had with a teammate and how you resolved it.", label: "behavioral", source: "real" },
  { text: "Give me an example of when you had to prioritize multiple competing deadlines.", label: "behavioral", source: "real" },
  { text: "Tell me about a time you went above and beyond what was expected.", label: "behavioral", source: "real" },
  { text: "Describe a situation where you had to adapt quickly to change.", label: "behavioral", source: "real" },
  { text: "Walk me through a time you received critical feedback and how you handled it.", label: "behavioral", source: "real" },
  { text: "Tell me about your biggest professional achievement.", label: "behavioral", source: "real" },
  { text: "Describe a time when you had to say no to a stakeholder or manager.", label: "behavioral", source: "real" },
  { text: "Give me an example of a time you had to learn something completely new quickly.", label: "behavioral", source: "real" },
  { text: "Tell me about a time you identified a problem no one else saw.", label: "behavioral", source: "real" },
  { text: "Describe a situation where you had to manage up.", label: "behavioral", source: "real" },
  { text: "Walk me through a time you had to build consensus among disagreeing team members.", label: "behavioral", source: "real" },
  { text: "Tell me about a time you had to deliver bad news to a client or stakeholder.", label: "behavioral", source: "real" },
  { text: "Describe a project that didn't go as planned and what you did.", label: "behavioral", source: "real" },
  { text: "Give me an example of when you had to challenge the status quo.", label: "behavioral", source: "real" },
  { text: "Tell me about a time you mentored someone.", label: "behavioral", source: "real" },
  { text: "Describe a situation where you had to work with someone you didn't get along with.", label: "behavioral", source: "real" },
  { text: "Walk me through a time you had to make an unpopular decision.", label: "behavioral", source: "real" },
  { text: "Tell me about a time you had to navigate ambiguity.", label: "behavioral", source: "real" },
  { text: "Describe a time when you had to balance speed and quality.", label: "behavioral", source: "real" },
  { text: "Give me an example of a time you turned around a failing project.", label: "behavioral", source: "real" },
  { text: "Tell me about your experience working in a fast-paced environment.", label: "behavioral", source: "real" },
  { text: "Describe a situation where you had to gather requirements from multiple stakeholders.", label: "behavioral", source: "real" },
  { text: "Walk me through a time you had to debug a production issue under pressure.", label: "behavioral", source: "real" },
  { text: "Tell me about a time you had to refactor or rewrite a large codebase.", label: "behavioral", source: "real" },
  { text: "Describe a time when you had to onboard a new team member.", label: "behavioral", source: "real" },
  { text: "Can you share an experience where you had to handle a toxic team member?", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you disagreed with your manager's technical decision.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to push back on unrealistic deadlines.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through how you handled a major outage.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of a time you improved a process.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to work with a difficult product manager.", label: "behavioral", source: "synthetic" },
  { text: "Describe a project where you had to learn a new technology stack.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through a time you had to fire someone or manage poor performance.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to negotiate with another team for resources.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to make a tradeoff between technical debt and shipping.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of when you had to communicate technical concepts to non-technical stakeholders.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you inherited a messy codebase.", label: "behavioral", source: "synthetic" },
  { text: "Describe a time when you had to build something with tight constraints.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through a time you had to sunset or deprecate a feature.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to work across time zones with a distributed team.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to handle scope creep.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of when you had to choose between two good options.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about your leadership style.", label: "behavioral", source: "synthetic" },
  { text: "Describe a time when you had to manage conflicting priorities.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through how you approach code reviews.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to handle a security incident.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to optimize for performance.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of a time you had to write documentation for a complex system.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to migrate a legacy system.", label: "behavioral", source: "synthetic" },
  { text: "Describe a project where you had to consider accessibility.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through a time you had to handle a data breach or privacy concern.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to build trust with a new team.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to say yes to unreasonable demands.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to handle a project with unclear requirements.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to resolve a disagreement between team members.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of when you had to take initiative on a project.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through a time you had to handle a situation where you were understaffed.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to deal with a difficult client.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to work with legacy technology.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of when you had to make a decision that affected the entire team.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to handle a situation where the requirements changed mid-project.", label: "behavioral", source: "synthetic" },
  { text: "Describe a project where you had to work with a tight budget.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through a time you had to handle a situation where you had conflicting feedback.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to work with a team that had different working styles.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to handle a high-pressure situation.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of when you had to use your creativity to solve a problem.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to handle a situation where you had to learn from a mistake.", label: "behavioral", source: "synthetic" },
  { text: "Describe a project where you had to work with stakeholders who had conflicting interests.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through a time you had to handle a situation where you had to compromise.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to work on a project that was outside your comfort zone.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to handle a situation where you had to be diplomatic.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of when you had to use your emotional intelligence.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to handle a situation where you had to be patient.", label: "behavioral", source: "synthetic" },
  { text: "Describe a project where you had to work with a team that was spread across different locations.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through a time you had to handle a situation where you had to be resilient.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to work on a project that had a lot of uncertainty.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to handle a situation where you had to be adaptable.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of when you had to use your problem-solving skills.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to handle a situation where you had to be decisive.", label: "behavioral", source: "synthetic" },
  { text: "Describe a project where you had to work with a team that had different skill levels.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through a time you had to handle a situation where you had to be empathetic.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to work on a project that required a lot of collaboration.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to handle a situation where you had to be proactive.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of when you had to use your communication skills.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to handle a situation where you had to be accountable.", label: "behavioral", source: "synthetic" },
  { text: "Describe a project where you had to work with a team that had different cultural backgrounds.", label: "behavioral", source: "synthetic" },
  { text: "Walk me through a time you had to handle a situation where you had to be resourceful.", label: "behavioral", source: "synthetic" },
  { text: "Tell me about a time you had to work on a project that had a lot of moving parts.", label: "behavioral", source: "synthetic" },
  { text: "Describe a situation where you had to handle a situation where you had to be detail-oriented.", label: "behavioral", source: "synthetic" },
  { text: "Give me an example of when you had to use your analytical skills.", label: "behavioral", source: "synthetic" },

  // === DEEP_DIVE / SYSTEM DESIGN (120 examples) ===
  { text: "How would you design a URL shortener like bit.ly?", label: "deep_dive", source: "real" },
  { text: "Design a distributed rate limiter.", label: "deep_dive", source: "real" },
  { text: "How would you build a real-time chat application?", label: "deep_dive", source: "real" },
  { text: "Design Twitter's news feed.", label: "deep_dive", source: "real" },
  { text: "How would you design a ride-sharing service like Uber?", label: "deep_dive", source: "real" },
  { text: "Design a web crawler.", label: "deep_dive", source: "real" },
  { text: "How would you build a recommendation system?", label: "deep_dive", source: "real" },
  { text: "Design a distributed cache.", label: "deep_dive", source: "real" },
  { text: "How would you design a payment processing system?", label: "deep_dive", source: "real" },
  { text: "Design an auto-complete system.", label: "deep_dive", source: "real" },
  { text: "How would you build a search engine?", label: "deep_dive", source: "real" },
  { text: "Design a video streaming platform like Netflix.", label: "deep_dive", source: "real" },
  { text: "How would you design a messaging queue?", label: "deep_dive", source: "real" },
  { text: "Design an analytics dashboard that handles millions of events per second.", label: "deep_dive", source: "real" },
  { text: "How would you build a collaborative document editor like Google Docs?", label: "deep_dive", source: "real" },
  { text: "Design a load balancer.", label: "deep_dive", source: "real" },
  { text: "How would you design a logging and monitoring system?", label: "deep_dive", source: "real" },
  { text: "Design a key-value store.", label: "deep_dive", source: "real" },
  { text: "How would you build a CI/CD pipeline?", label: "deep_dive", source: "real" },
  { text: "Design an API gateway.", label: "deep_dive", source: "real" },
  { text: "How would you handle session management at scale?", label: "deep_dive", source: "real" },
  { text: "Design a file storage system like S3.", label: "deep_dive", source: "real" },
  { text: "How would you implement distributed consensus?", label: "deep_dive", source: "real" },
  { text: "Design a notification system.", label: "deep_dive", source: "real" },
  { text: "How would you build a leaderboard system for a game?", label: "deep_dive", source: "real" },
  { text: "Design an image resizing service.", label: "deep_dive", source: "real" },
  { text: "How would you handle idempotency in a distributed system?", label: "deep_dive", source: "real" },
  { text: "Design a job scheduler.", label: "deep_dive", source: "real" },
  { text: "How would you implement rate limiting for an API?", label: "deep_dive", source: "real" },
  { text: "Design a configuration management system.", label: "deep_dive", source: "real" },
  { text: "Walk me through how you would design a social media platform.", label: "deep_dive", source: "synthetic" },
  { text: "How would you approach designing an e-commerce checkout system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling webhooks at scale.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a feature flag system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a distributed task queue.", label: "deep_dive", source: "synthetic" },
  { text: "How would you handle database sharding?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for A/B testing.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a spam detection system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a caching strategy for a read-heavy application.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement event sourcing?", label: "deep_dive", source: "synthetic" },
  { text: "Design a metrics aggregation system.", label: "deep_dive", source: "synthetic" },
  { text: "How would you handle data consistency across microservices?", label: "deep_dive", source: "synthetic" },
  { text: "Design a pub-sub messaging system.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a text search engine?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing secrets and credentials.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement circuit breakers?", label: "deep_dive", source: "synthetic" },
  { text: "Design a data pipeline for ETL.", label: "deep_dive", source: "synthetic" },
  { text: "How would you handle backpressure in a streaming system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a user authentication system.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a real-time bidding system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a content delivery network.", label: "deep_dive", source: "synthetic" },
  { text: "How would you handle multi-tenancy in a SaaS application?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing database migrations.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement optimistic locking?", label: "deep_dive", source: "synthetic" },
  { text: "Design a health check and service discovery system.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a recommendation engine for an e-commerce site?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling email at scale.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement pagination for a large dataset?", label: "deep_dive", source: "synthetic" },
  { text: "Design a schema registry for event-driven architectures.", label: "deep_dive", source: "synthetic" },
  { text: "How would you handle cross-region replication?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for generating unique IDs at scale.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement sagas for distributed transactions?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for feature rollout and canary deployments.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a sentiment analysis pipeline?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling timezone complexities.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement soft deletes in a database?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing API versioning.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a plagiarism detection system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling GDPR data deletion requests.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement leader election in a distributed system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for collecting and aggregating user analytics.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a real-time collaboration tool?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing third-party integrations.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement request deduplication?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling partial failures.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a geospatial search system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing webhooks with retry logic.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement connection pooling?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling bot detection.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a document versioning system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing API rate limits per user.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement database indexing strategies?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling media uploads and processing.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a recommendation system for job matching?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing feature flags with targeting.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement distributed tracing?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling batch processing jobs.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a fraud detection system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing user roles and permissions.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement database connection failover?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling inventory management.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a URL routing system for a large application?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing API keys and tokens.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement data masking for PII?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling tax calculation across regions.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a real-time stock ticker?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing shipping and logistics.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement blue-green deployments?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling surge pricing.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a chatbot architecture?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing database backups.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement request batching?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling partial updates in REST APIs.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a code review automation system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing environment-specific configs.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement database read replicas?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling concurrent edits.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a machine learning model serving system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing API deprecation.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement database partitioning strategies?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling webhook signature verification.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a log aggregation and analysis system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing cache invalidation.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement database query optimization?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling traffic spikes.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a content moderation system?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for managing schema evolution.", label: "deep_dive", source: "synthetic" },
  { text: "How would you implement database dead letter queues?", label: "deep_dive", source: "synthetic" },
  { text: "Design a system for handling partial payments.", label: "deep_dive", source: "synthetic" },
  { text: "How would you build a customer support ticket routing system?", label: "deep_dive", source: "synthetic" },

  // === CODING (100 examples) ===
  { text: "Write a function to reverse a linked list.", label: "coding", source: "real" },
  { text: "Implement a LRU cache.", label: "coding", source: "real" },
  { text: "Write a function to find the maximum subarray sum.", label: "coding", source: "real" },
  { text: "Implement a binary search tree with insert and delete operations.", label: "coding", source: "real" },
  { text: "Write a function to check if two strings are anagrams.", label: "coding", source: "real" },
  { text: "Implement a priority queue using a heap.", label: "coding", source: "real" },
  { text: "Write a function to merge two sorted arrays.", label: "coding", source: "real" },
  { text: "Implement a trie data structure.", label: "coding", source: "real" },
  { text: "Write a function to find the first non-repeating character in a string.", label: "coding", source: "real" },
  { text: "Implement a graph using adjacency lists and perform BFS.", label: "coding", source: "real" },
  { text: "Write a function to detect a cycle in a linked list.", label: "coding", source: "real" },
  { text: "Implement a stack that supports push, pop, and min operations in O(1).", label: "coding", source: "real" },
  { text: "Write a function to find the intersection of two arrays.", label: "coding", source: "real" },
  { text: "Implement a queue using two stacks.", label: "coding", source: "real" },
  { text: "Write a function to serialize and deserialize a binary tree.", label: "coding", source: "real" },
  { text: "Implement a hash map from scratch.", label: "coding", source: "real" },
  { text: "Write a function to find all permutations of a string.", label: "coding", source: "real" },
  { text: "Implement a balanced binary search tree.", label: "coding", source: "real" },
  { text: "Write a function to sort an array using quicksort.", label: "coding", source: "real" },
  { text: "Implement a rate limiter.", label: "coding", source: "real" },
  { text: "Write a function to find the longest common subsequence.", label: "coding", source: "synthetic" },
  { text: "Implement a bloom filter.", label: "coding", source: "synthetic" },
  { text: "Write a function to find the kth largest element.", label: "coding", source: "synthetic" },
  { text: "Implement consistent hashing.", label: "coding", source: "synthetic" },
  { text: "Write a function to validate a binary search tree.", label: "coding", source: "synthetic" },
  { text: "Implement a thread-safe singleton pattern.", label: "coding", source: "synthetic" },
  { text: "Write a function to find the shortest path in a maze.", label: "coding", source: "synthetic" },
  { text: "Implement a debounce function in JavaScript.", label: "coding", source: "synthetic" },
  { text: "Write a function to flatten a nested array.", label: "coding", source: "synthetic" },
  { text: "Implement a promise pool.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple event emitter.", label: "coding", source: "synthetic" },
  { text: "Implement a memoization decorator.", label: "coding", source: "synthetic" },
  { text: "Write a function to deep clone an object.", label: "coding", source: "synthetic" },
  { text: "Implement a throttle function.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement currying.", label: "coding", source: "synthetic" },
  { text: "Implement a simple pub-sub pattern.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement exponential backoff.", label: "coding", source: "synthetic" },
  { text: "Implement an LRU cache with O(1) operations.", label: "coding", source: "synthetic" },
  { text: "Write a function to find the longest palindromic substring.", label: "coding", source: "synthetic" },
  { text: "Implement a topological sort.", label: "coding", source: "synthetic" },
  { text: "Write a function to find all subsets of a set.", label: "coding", source: "synthetic" },
  { text: "Implement a union-find data structure.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple regex matcher.", label: "coding", source: "synthetic" },
  { text: "Implement a segment tree.", label: "coding", source: "synthetic" },
  { text: "Write a function to find the edit distance between two strings.", label: "coding", source: "synthetic" },
  { text: "Implement a distributed lock using Redis.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple load balancer.", label: "coding", source: "synthetic" },
  { text: "Implement a ring buffer.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple in-memory database.", label: "coding", source: "synthetic" },
  { text: "Implement a skip list.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple HTTP server.", label: "coding", source: "synthetic" },
  { text: "Implement a B-tree.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple compiler.", label: "coding", source: "synthetic" },
  { text: "Implement a write-ahead log.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple virtual machine.", label: "coding", source: "synthetic" },
  { text: "Implement a log-structured merge tree.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple garbage collector.", label: "coding", source: "synthetic" },
  { text: "Implement a concurrent hash map.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple DNS resolver.", label: "coding", source: "synthetic" },
  { text: "Implement a consensus algorithm like Raft.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple TCP proxy.", label: "coding", source: "synthetic" },
  { text: "Implement snapshot isolation.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple blockchain.", label: "coding", source: "synthetic" },
  { text: "Implement a vector clock.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement Paxos.", label: "coding", source: "synthetic" },
  { text: "Implement a gossip protocol.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a simple CRDT.", label: "coding", source: "synthetic" },
  { text: "Implement a Merkle tree.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement Byzantine fault tolerance.", label: "coding", source: "synthetic" },
  { text: "Implement a distributed transaction coordinator.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement two-phase commit.", label: "coding", source: "synthetic" },
  { text: "Implement an SSTable.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a memtable with WAL.", label: "coding", source: "synthetic" },
  { text: "Implement a bloom filter for duplicate detection.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement HyperLogLog.", label: "coding", source: "synthetic" },
  { text: "Implement a count-min sketch.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement reservoir sampling.", label: "coding", source: "synthetic" },
  { text: "Implement a t-digest.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement exponential moving average.", label: "coding", source: "synthetic" },
  { text: "Implement a discrete event simulator.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a neural network from scratch.", label: "coding", source: "synthetic" },
  { text: "Implement a decision tree.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement k-means clustering.", label: "coding", source: "synthetic" },
  { text: "Implement linear regression.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement gradient descent.", label: "coding", source: "synthetic" },
  { text: "Implement a convolutional neural network layer.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement an RNN cell.", label: "coding", source: "synthetic" },
  { text: "Implement an attention mechanism.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement a transformer block.", label: "coding", source: "synthetic" },
  { text: "Implement a BPE tokenizer.", label: "coding", source: "synthetic" },
  { text: "Write a function to implement beam search.", label: "coding", source: "synthetic" },

  // === CLARIFICATION (80 examples) ===
  { text: "Can you clarify what you mean by that?", label: "clarification", source: "real" },
  { text: "What do you mean by 'eventual consistency'?", label: "clarification", source: "real" },
  { text: "Could you explain that in more detail?", label: "clarification", source: "real" },
  { text: "I didn't quite understand your question. Could you rephrase it?", label: "clarification", source: "real" },
  { text: "When you say 'scale', do you mean horizontally or vertically?", label: "clarification", source: "real" },
  { text: "Can you break that down for me?", label: "clarification", source: "real" },
  { text: "What exactly are you looking for here?", label: "clarification", source: "real" },
  { text: "I'm not sure I follow. Can you give me more context?", label: "clarification", source: "real" },
  { text: "Do you mean how it works internally or how to use it?", label: "clarification", source: "real" },
  { text: "Can you unpack that a bit?", label: "clarification", source: "real" },
  { text: "What do you mean by 'reasonable latency'?", label: "clarification", source: "real" },
  { text: "Could you elaborate on the requirements?", label: "clarification", source: "real" },
  { text: "I'm confused about the scope. Is this for a single region or global?", label: "clarification", source: "real" },
  { text: "What do you mean by 'high availability' in this context?", label: "clarification", source: "real" },
  { text: "Can you clarify the constraints?", label: "clarification", source: "real" },
  { text: "Are you asking about the architecture or the implementation?", label: "clarification", source: "real" },
  { text: "What do you mean by 'efficient'?", label: "clarification", source: "real" },
  { text: "Could you rephrase that? I'm not sure I understand.", label: "clarification", source: "real" },
  { text: "Do you mean how to handle failures or how to prevent them?", label: "clarification", source: "real" },
  { text: "Can you be more specific about what you're looking for?", label: "clarification", source: "real" },
  { text: "What do you mean by 'real-time'?", label: "clarification", source: "synthetic" },
  { text: "Could you clarify the data volume we're talking about?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure which approach you're referring to. Can you clarify?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'best practices'?", label: "clarification", source: "synthetic" },
  { text: "Can you explain what you mean by 'event-driven'?", label: "clarification", source: "synthetic" },
  { text: "Are you asking about read-heavy or write-heavy workloads?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'fault tolerance'?", label: "clarification", source: "synthetic" },
  { text: "Could you clarify the timeline for this?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure I understand the question. Can you give me an example?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'scalable'?", label: "clarification", source: "synthetic" },
  { text: "Could you explain the business context?", label: "clarification", source: "synthetic" },
  { text: "Do you mean how to monitor or how to alert?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'secure'?", label: "clarification", source: "synthetic" },
  { text: "Can you clarify what success looks like?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure which technology you're referring to. Can you clarify?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'performant'?", label: "clarification", source: "synthetic" },
  { text: "Could you clarify the user flow?", label: "clarification", source: "synthetic" },
  { text: "Are you asking about the API design or the database schema?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'robust'?", label: "clarification", source: "synthetic" },
  { text: "Can you explain what you mean by 'microservices'?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure about the scale. Are we talking thousands or millions?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'latency-sensitive'?", label: "clarification", source: "synthetic" },
  { text: "Could you clarify the deployment model?", label: "clarification", source: "synthetic" },
  { text: "Do you mean synchronous or asynchronous processing?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'high throughput'?", label: "clarification", source: "synthetic" },
  { text: "Can you clarify the error handling requirements?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure I understand the question. Can you rephrase?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'reliable'?", label: "clarification", source: "synthetic" },
  { text: "Could you explain the data model?", label: "clarification", source: "synthetic" },
  { text: "Are you asking about batch or streaming?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'maintainable'?", label: "clarification", source: "synthetic" },
  { text: "Can you clarify the integration points?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure about the constraints. Can you list them?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'observable'?", label: "clarification", source: "synthetic" },
  { text: "Could you explain the failure modes?", label: "clarification", source: "synthetic" },
  { text: "Do you mean how to test or how to deploy?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'resilient'?", label: "clarification", source: "synthetic" },
  { text: "Can you clarify the security requirements?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure I understand the architecture. Can you draw it?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'cost-effective'?", label: "clarification", source: "synthetic" },
  { text: "Could you explain the trade-offs?", label: "clarification", source: "synthetic" },
  { text: "Are you asking about the short-term or long-term solution?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'flexible'?", label: "clarification", source: "synthetic" },
  { text: "Can you clarify the performance requirements?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure about the scope. Can you define it?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'simple'?", label: "clarification", source: "synthetic" },
  { text: "Could you explain the user experience you're aiming for?", label: "clarification", source: "synthetic" },
  { text: "Do you mean how to build or how to operate?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'elegant'?", label: "clarification", source: "synthetic" },
  { text: "Can you clarify the data retention policy?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure I understand the question. Can you provide more details?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'modern'?", label: "clarification", source: "synthetic" },
  { text: "Could you explain the compliance requirements?", label: "clarification", source: "synthetic" },
  { text: "Are you asking about the frontend or backend?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'industry standard'?", label: "clarification", source: "synthetic" },
  { text: "Can you clarify the monitoring requirements?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure about the budget. Can you share it?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'production-ready'?", label: "clarification", source: "synthetic" },
  { text: "Could you explain the disaster recovery requirements?", label: "clarification", source: "synthetic" },
  { text: "Do you mean active-active or active-passive?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'cloud-native'?", label: "clarification", source: "synthetic" },
  { text: "Can you clarify the multi-tenancy requirements?", label: "clarification", source: "synthetic" },
  { text: "I'm not sure I understand the question. Can you give me the context?", label: "clarification", source: "synthetic" },
  { text: "What do you mean by 'serverless'?", label: "clarification", source: "synthetic" },

  // === FOLLOW_UP (60 examples) ===
  { text: "What happened next?", label: "follow_up", source: "real" },
  { text: "Then what did you do?", label: "follow_up", source: "real" },
  { text: "How did that turn out?", label: "follow_up", source: "real" },
  { text: "What was the result?", label: "follow_up", source: "real" },
  { text: "Did you face any challenges after that?", label: "follow_up", source: "real" },
  { text: "How did you handle that situation?", label: "follow_up", source: "real" },
  { text: "What did you learn from that experience?", label: "follow_up", source: "real" },
  { text: "Can you go deeper into that?", label: "follow_up", source: "real" },
  { text: "Tell me more about that part.", label: "follow_up", source: "real" },
  { text: "What did the team think about that?", label: "follow_up", source: "real" },
  { text: "How did you measure the success?", label: "follow_up", source: "real" },
  { text: "What would you do differently next time?", label: "follow_up", source: "real" },
  { text: "How did you convince the stakeholders?", label: "follow_up", source: "real" },
  { text: "What was the biggest obstacle?", label: "follow_up", source: "real" },
  { text: "How long did that take?", label: "follow_up", source: "real" },
  { text: "What tools did you use?", label: "follow_up", source: "real" },
  { text: "How did you validate the solution?", label: "follow_up", source: "real" },
  { text: "What was the team's reaction?", label: "follow_up", source: "real" },
  { text: "How did you handle the pushback?", label: "follow_up", source: "real" },
  { text: "What metrics did you track?", label: "follow_up", source: "real" },
  { text: "How did you prioritize the tasks?", label: "follow_up", source: "synthetic" },
  { text: "What was the most surprising thing you learned?", label: "follow_up", source: "synthetic" },
  { text: "How did you communicate the changes?", label: "follow_up", source: "synthetic" },
  { text: "What was the rollback plan?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the edge cases?", label: "follow_up", source: "synthetic" },
  { text: "What was the performance impact?", label: "follow_up", source: "synthetic" },
  { text: "How did you test it?", label: "follow_up", source: "synthetic" },
  { text: "What was the user feedback?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the scale?", label: "follow_up", source: "synthetic" },
  { text: "What was the cost implication?", label: "follow_up", source: "synthetic" },
  { text: "How did you ensure reliability?", label: "follow_up", source: "synthetic" },
  { text: "What was the maintenance overhead?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the security?", label: "follow_up", source: "synthetic" },
  { text: "What was the monitoring strategy?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the data migration?", label: "follow_up", source: "synthetic" },
  { text: "What was the compliance requirement?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the integration?", label: "follow_up", source: "synthetic" },
  { text: "What was the deployment process?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the documentation?", label: "follow_up", source: "synthetic" },
  { text: "What was the onboarding process?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the training?", label: "follow_up", source: "synthetic" },
  { text: "What was the support model?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the incident response?", label: "follow_up", source: "synthetic" },
  { text: "What was the disaster recovery plan?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the capacity planning?", label: "follow_up", source: "synthetic" },
  { text: "What was the cost optimization strategy?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the vendor management?", label: "follow_up", source: "synthetic" },
  { text: "What was the stakeholder management approach?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the scope changes?", label: "follow_up", source: "synthetic" },
  { text: "What was the risk mitigation strategy?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the dependencies?", label: "follow_up", source: "synthetic" },
  { text: "What was the quality assurance process?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the performance optimization?", label: "follow_up", source: "synthetic" },
  { text: "What was the caching strategy?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the database scaling?", label: "follow_up", source: "synthetic" },
  { text: "What was the API design approach?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the authentication?", label: "follow_up", source: "synthetic" },
  { text: "What was the authorization model?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the data consistency?", label: "follow_up", source: "synthetic" },
  { text: "What was the event sourcing approach?", label: "follow_up", source: "synthetic" },
  { text: "How did you handle the CQRS implementation?", label: "follow_up", source: "synthetic" },

  // === EXAMPLE_REQUEST (50 examples) ===
  { text: "Can you give me an example of that?", label: "example_request", source: "real" },
  { text: "Provide a concrete example.", label: "example_request", source: "real" },
  { text: "Show me a specific instance.", label: "example_request", source: "real" },
  { text: "What is a real-world example of this?", label: "example_request", source: "real" },
  { text: "Give me a practical case.", label: "example_request", source: "real" },
  { text: "Can you illustrate with an example?", label: "example_request", source: "real" },
  { text: "For example, how would that work?", label: "example_request", source: "real" },
  { text: "Can you walk me through a real example?", label: "example_request", source: "real" },
  { text: "What does that look like in practice?", label: "example_request", source: "real" },
  { text: "Can you show me a code example?", label: "example_request", source: "real" },
  { text: "Give me a scenario where this applies.", label: "example_request", source: "synthetic" },
  { text: "Can you provide a use case?", label: "example_request", source: "synthetic" },
  { text: "What would be a good example of this?", label: "example_request", source: "synthetic" },
  { text: "Can you demonstrate with a concrete example?", label: "example_request", source: "synthetic" },
  { text: "Show me how this works in real life.", label: "example_request", source: "synthetic" },
  { text: "Can you give me a specific example from your experience?", label: "example_request", source: "synthetic" },
  { text: "What is an example of this pattern?", label: "example_request", source: "synthetic" },
  { text: "Can you provide a real-world scenario?", label: "example_request", source: "synthetic" },
  { text: "Give me a concrete instance where this mattered.", label: "example_request", source: "synthetic" },
  { text: "Can you illustrate this with a practical example?", label: "example_request", source: "synthetic" },
  { text: "What does this look like in a production environment?", label: "example_request", source: "synthetic" },
  { text: "Can you show me an example from your past work?", label: "example_request", source: "synthetic" },
  { text: "Give me a specific case study.", label: "example_request", source: "synthetic" },
  { text: "Can you provide an example with numbers?", label: "example_request", source: "synthetic" },
  { text: "What is a good counter-example?", label: "example_request", source: "synthetic" },
  { text: "Can you give me a before-and-after example?", label: "example_request", source: "synthetic" },
  { text: "Show me an example of the error handling.", label: "example_request", source: "synthetic" },
  { text: "Can you provide an example of the API response?", label: "example_request", source: "synthetic" },
  { text: "Give me an example of the database schema.", label: "example_request", source: "synthetic" },
  { text: "Can you show me an example of the deployment config?", label: "example_request", source: "synthetic" },
  { text: "What is an example of a good test case?", label: "example_request", source: "synthetic" },
  { text: "Can you give me an example of the monitoring dashboard?", label: "example_request", source: "synthetic" },
  { text: "Show me an example of the logging format.", label: "example_request", source: "synthetic" },
  { text: "Can you provide an example of the CI/CD pipeline?", label: "example_request", source: "synthetic" },
  { text: "Give me an example of the infrastructure setup.", label: "example_request", source: "synthetic" },
  { text: "Can you show me an example of the Docker compose file?", label: "example_request", source: "synthetic" },
  { text: "What is an example of the Kubernetes manifest?", label: "example_request", source: "synthetic" },
  { text: "Can you give me an example of the Terraform configuration?", label: "example_request", source: "synthetic" },
  { text: "Show me an example of the CloudFormation template.", label: "example_request", source: "synthetic" },
  { text: "Can you provide an example of the Ansible playbook?", label: "example_request", source: "synthetic" },
  { text: "Give me an example of the Puppet manifest.", label: "example_request", source: "synthetic" },
  { text: "Can you show me an example of the Chef recipe?", label: "example_request", source: "synthetic" },
  { text: "What is an example of the SaltStack state?", label: "example_request", source: "synthetic" },
  { text: "Can you give me an example of the Vagrantfile?", label: "example_request", source: "synthetic" },
  { text: "Show me an example of the Packer template.", label: "example_request", source: "synthetic" },
  { text: "Can you provide an example of the Helm chart?", label: "example_request", source: "synthetic" },
  { text: "Give me an example of the Kustomize overlay.", label: "example_request", source: "synthetic" },

  // === SUMMARY_PROBE (40 examples) ===
  { text: "So to summarize, you're saying...", label: "summary_probe", source: "real" },
  { text: "Let me make sure I understand.", label: "summary_probe", source: "real" },
  { text: "If I understood correctly...", label: "summary_probe", source: "real" },
  { text: "So you are saying that...", label: "summary_probe", source: "real" },
  { text: "Am I right that...", label: "summary_probe", source: "real" },
  { text: "To confirm my understanding...", label: "summary_probe", source: "real" },
  { text: "Did I get that right?", label: "summary_probe", source: "real" },
  { text: "So the key points are...", label: "summary_probe", source: "real" },
  { text: "Let me paraphrase what you said.", label: "summary_probe", source: "real" },
  { text: "So in other words...", label: "summary_probe", source: "real" },
  { text: "Just to clarify, you mean...", label: "summary_probe", source: "real" },
  { text: "So essentially...", label: "summary_probe", source: "real" },
  { text: "If I may summarize...", label: "summary_probe", source: "real" },
  { text: "So the main takeaway is...", label: "summary_probe", source: "real" },
  { text: "Let me recap what I've heard.", label: "summary_probe", source: "real" },
  { text: "So basically...", label: "summary_probe", source: "real" },
  { text: "To rephrase what you're saying...", label: "summary_probe", source: "real" },
  { text: "So the bottom line is...", label: "summary_probe", source: "real" },
  { text: "Let me see if I have this straight.", label: "summary_probe", source: "real" },
  { text: "So what you're telling me is...", label: "summary_probe", source: "real" },
  { text: "To make sure we're on the same page...", label: "summary_probe", source: "synthetic" },
  { text: "So the conclusion is...", label: "summary_probe", source: "synthetic" },
  { text: "Let me verify my understanding.", label: "summary_probe", source: "synthetic" },
  { text: "So the core idea is...", label: "summary_probe", source: "synthetic" },
  { text: "To restate what you said...", label: "summary_probe", source: "synthetic" },
  { text: "So the gist of it is...", label: "summary_probe", source: "synthetic" },
  { text: "Let me double-check my understanding.", label: "summary_probe", source: "synthetic" },
  { text: "So the main argument is...", label: "summary_probe", source: "synthetic" },
  { text: "To encapsulate what you've said...", label: "summary_probe", source: "synthetic" },
  { text: "So the crux of the matter is...", label: "summary_probe", source: "synthetic" },
  { text: "Let me confirm what I heard.", label: "summary_probe", source: "synthetic" },
  { text: "So the fundamental point is...", label: "summary_probe", source: "synthetic" },
  { text: "To boil it down...", label: "summary_probe", source: "synthetic" },
  { text: "So the essence is...", label: "summary_probe", source: "synthetic" },
  { text: "Let me make sure I have the key points.", label: "summary_probe", source: "synthetic" },
  { text: "So the primary concern is...", label: "summary_probe", source: "synthetic" },
  { text: "To distill what you've said...", label: "summary_probe", source: "synthetic" },
  { text: "So the overarching theme is...", label: "summary_probe", source: "synthetic" },
  { text: "Let me ensure I understand correctly.", label: "summary_probe", source: "synthetic" },
  { text: "So the central idea is...", label: "summary_probe", source: "synthetic" },

  // === GENERAL (100 examples) ===
  { text: "How are you doing today?", label: "general", source: "real" },
  { text: "Tell me about yourself.", label: "general", source: "real" },
  { text: "What are your strengths?", label: "general", source: "real" },
  { text: "What are your weaknesses?", label: "general", source: "real" },
  { text: "Why do you want to work here?", label: "general", source: "real" },
  { text: "Where do you see yourself in five years?", label: "general", source: "real" },
  { text: "What interests you about this role?", label: "general", source: "real" },
  { text: "Do you have any questions for me?", label: "general", source: "real" },
  { text: "What motivates you?", label: "general", source: "real" },
  { text: "How do you handle stress?", label: "general", source: "real" },
  { text: "What is your ideal work environment?", label: "general", source: "real" },
  { text: "How do you stay organized?", label: "general", source: "real" },
  { text: "What are your salary expectations?", label: "general", source: "real" },
  { text: "Why are you leaving your current job?", label: "general", source: "real" },
  { text: "What do you know about our company?", label: "general", source: "real" },
  { text: "What makes you a good fit for this team?", label: "general", source: "real" },
  { text: "How do you handle feedback?", label: "general", source: "real" },
  { text: "What do you do for fun outside of work?", label: "general", source: "real" },
  { text: "How do you keep up with industry trends?", label: "general", source: "real" },
  { text: "What is your favorite programming language and why?", label: "general", source: "real" },
  { text: "Describe your ideal manager.", label: "general", source: "synthetic" },
  { text: "What do you value most in a team?", label: "general", source: "synthetic" },
  { text: "How do you approach problem-solving?", label: "general", source: "synthetic" },
  { text: "What is the most important thing you've learned in your career?", label: "general", source: "synthetic" },
  { text: "How do you handle tight deadlines?", label: "general", source: "synthetic" },
  { text: "What do you think sets you apart from other candidates?", label: "general", source: "synthetic" },
  { text: "How do you handle ambiguity?", label: "general", source: "synthetic" },
  { text: "What is your approach to continuous learning?", label: "general", source: "synthetic" },
  { text: "How do you balance work and life?", label: "general", source: "synthetic" },
  { text: "What do you think are the biggest challenges in our industry?", label: "general", source: "synthetic" },
  { text: "How do you handle disagreements with teammates?", label: "general", source: "synthetic" },
  { text: "What is your communication style?", label: "general", source: "synthetic" },
  { text: "How do you handle changing requirements?", label: "general", source: "synthetic" },
  { text: "What do you think makes a good engineer?", label: "general", source: "synthetic" },
  { text: "How do you approach debugging?", label: "general", source: "synthetic" },
  { text: "What is your experience with agile methodologies?", label: "general", source: "synthetic" },
  { text: "How do you handle technical debt?", label: "general", source: "synthetic" },
  { text: "What do you think about remote work?", label: "general", source: "synthetic" },
  { text: "How do you handle imposter syndrome?", label: "general", source: "synthetic" },
  { text: "What is your approach to mentoring?", label: "general", source: "synthetic" },
  { text: "How do you handle burnout?", label: "general", source: "synthetic" },
  { text: "What do you think about pair programming?", label: "general", source: "synthetic" },
  { text: "How do you handle legacy code?", label: "general", source: "synthetic" },
  { text: "What is your experience with microservices?", label: "general", source: "synthetic" },
  { text: "How do you handle on-call rotations?", label: "general", source: "synthetic" },
  { text: "What do you think about code reviews?", label: "general", source: "synthetic" },
  { text: "How do you handle production incidents?", label: "general", source: "synthetic" },
  { text: "What is your experience with cloud platforms?", label: "general", source: "synthetic" },
  { text: "How do you handle database migrations?", label: "general", source: "synthetic" },
  { text: "What do you think about test-driven development?", label: "general", source: "synthetic" },
  { text: "How do you handle performance optimization?", label: "general", source: "synthetic" },
  { text: "What is your experience with CI/CD?", label: "general", source: "synthetic" },
  { text: "How do you handle security in your applications?", label: "general", source: "synthetic" },
  { text: "What do you think about monorepos?", label: "general", source: "synthetic" },
  { text: "How do you handle cross-team collaboration?", label: "general", source: "synthetic" },
  { text: "What is your experience with open source?", label: "general", source: "synthetic" },
  { text: "How do you handle documentation?", label: "general", source: "synthetic" },
  { text: "What do you think about serverless architectures?", label: "general", source: "synthetic" },
  { text: "How do you handle data privacy?", label: "general", source: "synthetic" },
  { text: "What is your experience with machine learning?", label: "general", source: "synthetic" },
  { text: "How do you handle technical interviews?", label: "general", source: "synthetic" },
  { text: "What do you think about domain-driven design?", label: "general", source: "synthetic" },
  { text: "How do you handle event-driven architectures?", label: "general", source: "synthetic" },
  { text: "What is your experience with GraphQL?", label: "general", source: "synthetic" },
  { text: "How do you handle API design?", label: "general", source: "synthetic" },
  { text: "What do you think about NoSQL databases?", label: "general", source: "synthetic" },
  { text: "How do you handle containerization?", label: "general", source: "synthetic" },
  { text: "What is your experience with Kubernetes?", label: "general", source: "synthetic" },
  { text: "How do you handle monitoring and observability?", label: "general", source: "synthetic" },
  { text: "What do you think about infrastructure as code?", label: "general", source: "synthetic" },
  { text: "How do you handle dependency management?", label: "general", source: "synthetic" },
  { text: "What is your experience with TypeScript?", label: "general", source: "synthetic" },
  { text: "How do you handle state management in frontend?", label: "general", source: "synthetic" },
  { text: "What do you think about functional programming?", label: "general", source: "synthetic" },
  { text: "How do you handle concurrency?", label: "general", source: "synthetic" },
  { text: "What is your experience with Rust?", label: "general", source: "synthetic" },
  { text: "How do you handle memory management?", label: "general", source: "synthetic" },
  { text: "What do you think about WebAssembly?", label: "general", source: "synthetic" },
  { text: "How do you handle real-time data?", label: "general", source: "synthetic" },
  { text: "What is your experience with WebSockets?", label: "general", source: "synthetic" },
  { text: "How do you handle internationalization?", label: "general", source: "synthetic" },
  { text: "What do you think about progressive web apps?", label: "general", source: "synthetic" },
  { text: "How do you handle accessibility?", label: "general", source: "synthetic" },
  { text: "What is your experience with WebRTC?", label: "general", source: "synthetic" },
  { text: "How do you handle offline-first applications?", label: "general", source: "synthetic" },
  { text: "What do you think about blockchain?", label: "general", source: "synthetic" },
  { text: "How do you handle big data?", label: "general", source: "synthetic" },
  { text: "What is your experience with data engineering?", label: "general", source: "synthetic" },
  { text: "How do you handle data visualization?", label: "general", source: "synthetic" },
  { text: "What do you think about low-code platforms?", label: "general", source: "synthetic" },
  { text: "How do you handle technical writing?", label: "general", source: "synthetic" },
  { text: "What is your experience with DevOps?", label: "general", source: "synthetic" },
  { text: "How do you handle site reliability engineering?", label: "general", source: "synthetic" },
  { text: "What do you think about platform engineering?", label: "general", source: "synthetic" },
  { text: "How do you handle chaos engineering?", label: "general", source: "synthetic" },
  { text: "What is your experience with data science?", label: "general", source: "synthetic" },
  { text: "How do you handle A/B testing?", label: "general", source: "synthetic" },
  { text: "What do you think about growth engineering?", label: "general", source: "synthetic" },
  { text: "How do you handle product analytics?", label: "general", source: "synthetic" },
  { text: "What is your experience with user research?", label: "general", source: "synthetic" },
  { text: "How do you handle design systems?", label: "general", source: "synthetic" },
  { text: "What do you think about design thinking?", label: "general", source: "synthetic" },
  { text: "How do you handle user experience design?", label: "general", source: "synthetic" },
];

export function getAllExamples(): TrainingExample[] {
  return [...EXAMPLES];
}

export function splitTrainTest(
  examples: TrainingExample[],
  testRatio: number,
  seed: number = 42,
): { train: TrainingExample[]; test: TrainingExample[] } {
  // Group by label for stratified split
  const byLabel = new Map<string, TrainingExample[]>();
  for (const ex of examples) {
    const arr = byLabel.get(ex.label) ?? [];
    arr.push(ex);
    byLabel.set(ex.label, arr);
  }

  // Deterministic shuffle
  const rng = mulberry32(seed);
  const train: TrainingExample[] = [];
  const test: TrainingExample[] = [];

  for (const [, group] of byLabel) {
    const shuffled = shuffleArray(group, rng);
    const splitIndex = Math.floor(shuffled.length * (1 - testRatio));
    train.push(...shuffled.slice(0, splitIndex));
    test.push(...shuffled.slice(splitIndex));
  }

  return { train: shuffleArray(train, rng), test: shuffleArray(test, rng) };
}

function shuffleArray<T>(array: T[], rng: () => number): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function mulberry32(a: number): () => number {
  return () => {
    let t = (a += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
