/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Open build: licensing is disabled and premium features are always unlocked. */
export declare function getHardwareId(): string
/** Open build compatibility shim - always resolves successfully. */
export declare function verifyGumroadKey(licenseKey: string): Promise<unknown>
export declare function applyMacosWindowStealth(windowNumber: number): void
export declare function removeMacosWindowStealth(windowNumber: number): void
export declare function applyMacosPrivateWindowStealth(windowNumber: number): void
export declare function removeMacosPrivateWindowStealth(windowNumber: number): void
export declare function verifyMacosStealthState(windowNumber: number): number
export declare function applyWindowsWindowStealth(hwndBuffer: Buffer): void
export declare function removeWindowsWindowStealth(hwndBuffer: Buffer): void
export declare function verifyWindowsStealthState(hwndBuffer: Buffer): number
/**
 * Represents information about a visible window.
 * Used by the Electron side for capture detection instead of spawning Python.
 */
export interface WindowInfo {
  windowNumber: number
  ownerName: string
  ownerPid: number
  windowTitle: string
  isOnScreen: boolean
  sharingState: number
}
/**
 * List all visible windows using Core Graphics.
 * This replaces the Python3 subprocess call to Quartz.CGWindowListCopyWindowInfo.
 *
 * NOTE: This is a placeholder implementation. Full CGWindowList integration
 * requires Core Graphics C API bindings that are complex to implement.
 * The Electron side has fallback to the existing Python3 approach.
 */
export declare function listVisibleWindows(): Array<WindowInfo>
/**
 * Check if any browser-based capture is active based on window titles.
 * Combines the Quartz window enumeration + browser check in a single native call.
 *
 * NOTE: This is a placeholder implementation. Full CGWindowList integration
 * requires Core Graphics C API bindings that are complex to implement.
 * The Electron side has fallback to the existing Python3 approach.
 */
export declare function checkBrowserCaptureWindows(): boolean
export interface AudioDeviceInfo {
  id: string
  name: string
}
export declare function getInputDevices(): Array<AudioDeviceInfo>
export declare function getOutputDevices(): Array<AudioDeviceInfo>
export declare class SystemAudioCapture {
  constructor(deviceId?: string | undefined | null, outputSampleRate?: number | undefined | null)
  getSampleRate(): number
  /** Sample rate of PCM buffers emitted to JS (after native polyphase resample). */
  getOutputSampleRate(): number
  start(callback: (...args: any[]) => any, onSpeechEnded?: (...args: any[]) => any | undefined | null): void
  stop(): void
}
export declare class MicrophoneCapture {
  constructor(deviceId?: string | undefined | null, outputSampleRate?: number | undefined | null)
  getSampleRate(): number
  getOutputSampleRate(): number
  start(callback: (...args: any[]) => any, onSpeechEnded?: (...args: any[]) => any | undefined | null): void
  stop(): void
}
